server:
  port: 9004

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost/AuthDB
    username: postgres
    password: 2392
  jpa:
    generate-ddl: true

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

